### ISSUE TITLE
회의록 업로드

### ISSUE THREAD

**Issue by GHeeJeon** [e-commerce-clone/e-commerce-clone#1]
주차별 업로드
readme에 요약해서?
pdf파일 통째로 업로드?

**Comment by GHeeJeon** [comment]
n주차 회의마다 pdf 링크를 걸어놓자!

**Comment by ksmfou98** [comment]
pdf 링크가 나을까요??

**Comment by GHeeJeon** [comment]
> pdf 링크가 나을까요??

pdf 원본 업로드해주시면 링크 추가해서 readme 수정할게요!

예시:
📎 n주차 회의 (클립을 클릭하면 pdf를 업로드 한 곳으로 이동)

**Comment by GHeeJeon** [comment]
해결 완료!
